package sanctuary.app.feature.dump.domain.model

import kotlinx.serialization.Serializable

/**
 * The enriched content of an AI-generated emotional insight.
 *
 * This is the core data generated by the Claude API based on a user's recording.
 * It contains structured analysis of the user's emotions, thoughts, and actionable advice.
 *
 * @property title Brief, user-friendly title of the insight
 * @property summary One-sentence summary of the main finding
 * @property fullSummary Detailed multi-paragraph summary
 * @property emotions List of detected emotional states (e.g., "Anxious", "Hopeful")
 * @property pathForward Specific, actionable advice for emotional growth
 * @property recordingType The type of recording: "dump", "question", "concern"
 * @property sentiment Overall sentiment: POSITIVE, NEGATIVE, or NEUTRAL
 */
@Serializable
data class InsightContent(
    val title: String,
    val summary: String,
    val fullSummary: String,
    val emotions: List<String>,
    val pathForward: String,
    val recordingType: String,
    val sentiment: Sentiment,
)

/**
 * Overall sentiment classification of the insight.
 *
 * - POSITIVE: User expressed hopeful, satisfied, or growth-oriented feelings
 * - NEGATIVE: User expressed sadness, anxiety, frustration, or concern
 * - NEUTRAL: Mixed sentiments or factual/neutral tone
 */
@Serializable
enum class Sentiment {
    POSITIVE, NEGATIVE, NEUTRAL
}

/**
 * A complete AI-generated emotional insight tied to a user's recording.
 *
 * This is the main model representing the output of the AI insight generation pipeline.
 * It combines the user's recording with Claude-generated analysis and insights.
 *
 * Lifecycle:
 * 1. PENDING: Request submitted, waiting to be processed
 * 2. GENERATING: AI is analyzing the recording
 * 3. SAVED: Successfully generated and stored
 * 4. ARCHIVED: User archived this insight (kept for 15 days then deleted)
 *
 * @property id Unique identifier for this insight
 * @property recordingId The ID of the recording this insight was generated from
 * @property content The structured AI-generated content
 * @property createdAt Timestamp when insight was generated (epoch ms)
 * @property isArchived Whether the user has archived this insight
 * @property archivedAt Timestamp when archived (epoch ms), null if not archived
 * @property status The lifecycle stage of this insight
 */
data class Insight(
    val id: String,
    val recordingId: String,
    val content: InsightContent,
    val createdAt: Long,
    val isArchived: Boolean = false,
    val archivedAt: Long? = null,
    val status: InsightStatus = InsightStatus.SAVED,
)

/**
 * Lifecycle states for insight generation and storage.
 *
 * - PENDING: Insight generation request created, awaiting processing
 * - GENERATING: API call in progress, generating insight from recording
 * - SAVED: Successfully generated and persisted to database
 * - ARCHIVED: User archived this insight; will be deleted after 15 days
 */
enum class InsightStatus {
    PENDING, GENERATING, SAVED, ARCHIVED
}
